const header=document.querySelector('[data-header]');const nav=document.querySelector('#site-nav');const toggle=document.querySelector('.menu-toggle');const links=[...document.querySelectorAll('.site-nav a')];
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>30),{passive:true});
toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.classList.toggle('is-open',open);document.body.style.overflow=open?'hidden':''});links.forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');document.body.style.overflow=''}));
const sections=[...document.querySelectorAll('main section[id]')];const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>observer.observe(s));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const heroVideo=document.querySelector('[data-hero-video]');const videoToggle=document.querySelector('[data-video-toggle]');if(heroVideo&&videoToggle){const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');const updateVideoToggle=()=>{const paused=heroVideo.paused;videoToggle.querySelector('span').textContent=paused?'▶':'Ⅱ';videoToggle.querySelector('b').textContent=paused?'Bewegung abspielen':'Bewegung pausieren';videoToggle.setAttribute('aria-label',paused?'Hintergrundvideo abspielen':'Hintergrundvideo pausieren')};if(reducedMotion.matches)heroVideo.pause();videoToggle.addEventListener('click',()=>heroVideo.paused?heroVideo.play():heroVideo.pause());heroVideo.addEventListener('play',updateVideoToggle);heroVideo.addEventListener('pause',updateVideoToggle);updateVideoToggle()}
const perspectiveTrack=document.querySelector('[data-perspective-track]');if(perspectiveTrack){const cards=[...perspectiveTrack.querySelectorAll('.perspective-card')];const current=document.querySelector('[data-perspective-current]');const previous=document.querySelector('[data-perspective-prev]');const next=document.querySelector('[data-perspective-next]');const progress=[...document.querySelectorAll('.perspective-progress span')];const targetLeft=index=>cards[index].offsetLeft-cards[0].offsetLeft;const activeCard=()=>cards.reduce((best,card,index)=>Math.abs(targetLeft(index)-perspectiveTrack.scrollLeft)<Math.abs(targetLeft(best)-perspectiveTrack.scrollLeft)?index:best,0);const updatePerspective=()=>{const index=activeCard();current.textContent=String(index+1).padStart(2,'0');previous.disabled=index===0;next.disabled=index===cards.length-1;progress.forEach((item,itemIndex)=>item.classList.toggle('active',itemIndex===index))};const goToPerspective=index=>{const target=Math.min(cards.length-1,Math.max(0,index));perspectiveTrack.scrollTo({left:targetLeft(target),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};previous.addEventListener('click',()=>goToPerspective(activeCard()-1));next.addEventListener('click',()=>goToPerspective(activeCard()+1));perspectiveTrack.addEventListener('keydown',event=>{const keyTargets={ArrowLeft:activeCard()-1,ArrowRight:activeCard()+1,Home:0,End:cards.length-1};if(keyTargets[event.key]===undefined)return;event.preventDefault();goToPerspective(keyTargets[event.key])});perspectiveTrack.addEventListener('scroll',updatePerspective,{passive:true});window.addEventListener('resize',updatePerspective,{passive:true});updatePerspective()}
const form=document.querySelector('[data-contact-form]');const status=form.querySelector('.form-status');const submit=form.querySelector('[type=submit]');const success=document.querySelector('[data-form-success]');const WEBHOOK_URL=window.EASTEND_CONFIG?.webhookUrl||'';
const MAX_FILE_BYTES=2*1024*1024;const fileInput=form.querySelector('[data-file-input]');const fileName=form.querySelector('[data-file-name]');const fileRemove=form.querySelector('[data-file-remove]');const fileField=fileInput.closest('.file-field');
const fileError=file=>{if(!file)return'';if(file.name.split('.').pop().toLowerCase()!=='pdf')return'Bitte laden Sie Ihre Unterlagen als PDF hoch.';if(file.size>MAX_FILE_BYTES)return'Die Datei ist größer als 2 MB. Bitte wählen Sie eine kleinere PDF.';if(file.size===0)return'Die Datei ist leer.';return''};
const formatSize=bytes=>bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1024/1024).toFixed(1).replace('.',',')} MB`;
const showFile=()=>{const file=fileInput.files[0];const error=fileError(file);fileName.textContent=error||(file?`${file.name} · ${formatSize(file.size)}`:'Keine Datei ausgewählt');fileField.classList.toggle('has-file',!!file&&!error);fileField.classList.toggle('has-error',!!error);fileRemove.hidden=!file};
fileInput.addEventListener('change',showFile);fileRemove.addEventListener('click',()=>{fileInput.value='';showFile();fileInput.focus()});
// Freundliche Hinweise statt der Browser-Standardmeldungen. Die Prüfung entspricht der in n8n.
const FIELDS=[['name','Name',f=>f.value.trim()?'':'Bitte geben Sie Ihren Namen an.'],['company','Unternehmen',f=>f.value.trim()?'':'Bitte nennen Sie Ihr Unternehmen.'],['email','E-Mail',f=>!f.value.trim()?'Bitte geben Sie Ihre E-Mail-Adresse an.':/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(f.value.trim())?'':'Diese E-Mail-Adresse scheint unvollständig zu sein.'],['topic','Anliegen',f=>f.value?'':'Bitte wählen Sie aus, worum es geht.'],['message','Nachricht',f=>!f.value.trim()?'Bitte schreiben Sie uns kurz, worum es geht.':f.value.trim().length<10?'Ein paar Worte mehr helfen uns, Ihr Anliegen einzuordnen.':''],['consent','Einwilligung',f=>f.checked?'':'Bitte bestätigen Sie die Einwilligung, damit wir Ihre Anfrage bearbeiten dürfen.']];
const setFieldError=(field,message)=>{const holder=field.type==='checkbox'?field.closest('label'):field.closest('label');let note=holder.nextElementSibling?.classList.contains('field-error')?holder.nextElementSibling:null;if(field.type!=='checkbox')note=holder.querySelector('.field-error');if(!message){holder.classList.remove('is-invalid');field.removeAttribute('aria-invalid');note?.remove();return}holder.classList.add('is-invalid');field.setAttribute('aria-invalid','true');if(!note){note=document.createElement('span');note.className='field-error';note.id=`${field.name}-error`;field.type==='checkbox'?holder.after(note):holder.append(note);field.setAttribute('aria-describedby',note.id)}note.textContent=message};
const validate=()=>{const missing=[];let first=null;FIELDS.forEach(([name,label,check])=>{const field=form.elements[name];const message=check(field);setFieldError(field,message);if(message){missing.push(label);first=first||field}});const fileProblem=fileError(fileInput.files[0]);if(fileProblem){missing.push('Anhang');first=first||fileInput}return{missing,first}};
FIELDS.forEach(([name,,check])=>{const field=form.elements[name];['input','change'].forEach(type=>field.addEventListener(type,()=>{if(field.getAttribute('aria-invalid'))setFieldError(field,check(field))}))});
const showSuccess=()=>{form.hidden=true;success.querySelector('[data-success-demo]').hidden=!!WEBHOOK_URL;success.hidden=false;success.classList.remove('is-shown');void success.offsetWidth;success.classList.add('is-shown');success.focus({preventScroll:true});success.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})};
success.querySelector('[data-form-again]').addEventListener('click',()=>{success.hidden=true;form.hidden=false;status.className='form-status';status.textContent='';form.elements.name.focus()});
form.addEventListener('submit',async event=>{event.preventDefault();status.className='form-status';status.textContent='';const{missing,first}=validate();if(missing.length){status.classList.add('error');status.textContent=`Fast geschafft – bitte prüfen Sie noch: ${missing.join(', ')}.`;first.focus();return}const data=new FormData(form);if(data.get('website')){showSuccess();return}data.delete('website');if(!fileInput.files[0])data.delete('attachment');data.set('source','eastend46-website');data.set('submittedAt',new Date().toISOString());submit.disabled=true;status.textContent='Wird übermittelt …';let serverError='';try{if(WEBHOOK_URL){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);const response=await fetch(WEBHOOK_URL,{method:'POST',body:data,signal:controller.signal});clearTimeout(timer);const result=await response.json().catch(()=>({}));if(!response.ok||result.ok===false){serverError=result.error||'';throw new Error('Webhook error')}}form.reset();showFile();status.textContent='';showSuccess()}catch(error){status.className='form-status error';status.textContent=serverError||'Das hat leider nicht geklappt. Bitte versuchen Sie es in einem Moment erneut oder schreiben Sie uns an dialog@eastend46.de.'}finally{submit.disabled=false}});
